# Generated by Django 5.2.8 on 2025-11-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_sheet', models.CharField(max_length=128)),
                ('table_section', models.CharField(max_length=256)),
                ('fabric_name', models.CharField(max_length=128)),
                ('height_gabarit_mm', models.PositiveIntegerField()),
                ('width_fabric_mm', models.PositiveIntegerField()),
                ('roll_height_info', models.CharField(blank=True, max_length=64)),
                ('gabarit_width_flag', models.BooleanField(default=False)),
                ('base_price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('surcharge_height_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('magnets_price_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.organization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
