# Generated by Django 5.2.8 on 2025-11-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bottom_fixation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='control_side',
            field=models.CharField(blank=True, help_text='Сторона керування (лівий/правий ланцюжок тощо)', max_length=32),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pvc_plank',
            field=models.BooleanField(default=False),
        ),
    ]
