# Generated by Django 5.2.8 on 2025-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_bottom_fixation_orderitem_control_side_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fabric_color_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код кольору тканини'),
        ),
    ]
