# Generated by Django 5.2.8 on 2025-11-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_fabric_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_brown_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_brown_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.249, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_graphite_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_graphite_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.837, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_oak_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_oak_price_eur',
            field=models.DecimalField(decimal_places=3, default=4.19, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_white_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_high_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.199, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_brown_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_brown_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.161, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_graphite_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_graphite_price_eur',
            field=models.DecimalField(decimal_places=3, default=4.448, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_white_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_box_low_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.161, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_mosel_external_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.797, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_mosel_external_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_mosel_internal_price_eur',
            field=models.DecimalField(decimal_places=3, default=3.461, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='adapter_mosel_internal_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bottom_wide_bar_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Довжина широкої нижньої планки 10/28, м.п.', max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bottom_wide_bar_price_eur_mp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за широку нижню планку 10/28, EUR/м.п.', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chain_weight_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chain_weight_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.084, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cord_copper_barrel_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна за одну фіксацію лески з мідною діжкою, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cord_copper_barrel_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість фіксацій лески з мідною діжкою, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cord_pvc_tension_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна за одну фіксацію лески ПВХ з дотяжкою, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cord_pvc_tension_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість фіксацій лески ПВХ з дотяжкою, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='eur_rate_at_creation',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Курс EUR на момент створення позиції', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_brown_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.154, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_brown_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_graphite_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.182, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_graphite_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_oak_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.182, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_oak_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=0.154, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='insert_plus8_white_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='magnet_fix_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна за одну магнітну фіксацію, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='magnet_fix_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість магнітних фіксацій, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metal_cord_fix_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна за одну металеву фіксацію лески, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metal_cord_fix_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість металевих фіксацій лески, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='middle_bracket_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за один проміжковий кронштейн, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='middle_bracket_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість проміжкових кронштейнів, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='motor_no_remote_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за один електродвигун без пульта, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='motor_no_remote_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість електродвигунів без пульта (під вимикач), шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='motor_with_remote_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за електродвигун з одноканальним пультом, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='motor_with_remote_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість електродвигунів з одноканальним пультом ДУ, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remote_15ch_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за 15-ти канальний пульт ДУ, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remote_15ch_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість 15-ти канальних пультів ДУ, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remote_5ch_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за 5-ти канальний пульт ДУ, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remote_5ch_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість 5-ти канальних пультів ДУ, шт'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_19_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_19_price_eur',
            field=models.DecimalField(decimal_places=3, default=1.048, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_25_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_25_price_eur',
            field=models.DecimalField(decimal_places=3, default=1.38, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_32_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_32_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.749, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_47_white_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shaft_47_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=7.437, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_bar_scotch_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Довжина скотчу на верхню планку (без свердління), м.п.', max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_bar_scotch_price_eur_mp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна скотчу на верхню планку, EUR/м.п.', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_brown_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_brown_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.455, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_graphite_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_graphite_price_eur',
            field=models.DecimalField(decimal_places=3, default=2.455, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_white_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_al_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=1.397, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_std_pvc_brown_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_std_pvc_brown_price_eur',
            field=models.DecimalField(decimal_places=3, default=1.879, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_std_pvc_white_m',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_profile_dn_std_pvc_white_price_eur',
            field=models.DecimalField(decimal_places=3, default=1.535, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_pvc_bar_tape_m',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Довжина верхньої планки ПВХ зі скотчем, м.п.', max_digits=8),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_pvc_bar_tape_price_eur_mp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна доплати за верхню планку ПВХ зі скотчем, EUR/м.п.', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_pvc_clip_pair_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна за одну пару кліпс, EUR/пара', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='top_pvc_clip_pair_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість кліпс для верхньої планки ПВХ, пар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='magnets_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ціна магнітної фіксації (може бути загальною або одиничною, залежно від логіки калькулятора)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='roll_height_info',
            field=models.CharField(blank=True, help_text="Текстова підказка типу 'Висота рулону, мм'", max_length=64),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Проміжна сума по позиції (без множення на quantity)', max_digits=12),
        ),
    ]
