# Generated by Django 5.2.8 on 2025-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_adapter_box_high_brown_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='metal_kronsht_price_eur',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Доплата за металеві кронштейни, EUR/шт', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='metal_kronsht_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість металеві кронштейни, шт'),
        ),
    ]
