# Generated by Django 5.2.8 on 2025-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename__columns_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='magnets_qty',
            field=models.PositiveIntegerField(default=0, help_text='Кількість магнітної фіксації'),
        ),
    ]
