# Generated by Django 5.2.8 on 2025-11-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_qty_fields2'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE orders_orderitem
                DROP COLUMN IF EXISTS magnets_fixation;
            """,
            reverse_sql="""
                ALTER TABLE orders_orderitem
                ADD COLUMN magnets_fixation boolean DEFAULT FALSE;
            """
        ),
    ]
