# Generated by Django 5.2.8 on 2025-11-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_create_order_component_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomponentitem',
            name='unit',
            field=models.CharField(help_text='Одиниця виміру (шт, м.п., компл. тощо)', max_length=32, verbose_name='Од. вим.'),
        ),
    ]
