# Generated by Django 5.2.8 on 2025-12-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_eur_rate_and_currencyrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='top_bar_scotch_price_eur',
            new_name='top_bar_scotch_price_eur_mp',
        ),
    ]
