# Generated by Django 5.2.8 on 2025-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_top_bar_scotch_price_eur_orderitem_top_bar_scotch_price_eur_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='GbDiffWidthMm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gb_width_mm',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
