# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_order_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="fabric_height_flag",
            field=models.BooleanField(default=False),
        ),
    ]
