# Generated by Django 5.2.8 on 2025-12-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_add_transaction_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('debit', 'Пришло від клієнта'), ('credit', 'Уход клієнту')], max_length=16),
        ),
    ]
