# Generated by Django 5.2.8 on 2025-12-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderitem_fabric_height_flag'),
        ('orders', '0030_transaction_payment_fields'),
    ]

    operations = [
    ]
