# Generated by Codex on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_merge_20251217_1205"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyAutoUpdateSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("auto_update", models.BooleanField(default=False)),
                ("update_times", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Автооновлення курсу",
                "verbose_name_plural": "Автооновлення курсу",
            },
        ),
    ]
