# Generated by Django 5.2.8 on 2025-12-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_extra_service'),
        ('orders', '0032_currency_auto_update_settings'),
    ]

    operations = [
    ]
