# Generated by Django 5.2.8 on 2025-12-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_order_soft_delete'),
        ('orders', '0033_merge_20251224_2317'),
    ]

    operations = [
    ]
