# Generated by Django 5.2.8 on 2026-02-07 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_orderfabricitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiondeletionhistory',
            options={'ordering': ['-deleted_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Знижка клієнта на момент створення замовлення, %', max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderfabricitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactiondeletionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
