# Generated by Django 5.2.8 on 2026-04-09 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_orderfabricitem_fabric_color_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMosquitoComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=32)),
                ('length_mm', models.PositiveIntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=9)),
                ('price_usd', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosquito_component_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Комплектуюча до москітних сіток в замовленні',
                'verbose_name_plural': 'Комплектуючі до москітних сіток в замовленні',
            },
        ),
        migrations.CreateModel(
            name='OrderMosquitoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=255)),
                ('profile_color', models.CharField(blank=True, default='', max_length=100)),
                ('mesh_type', models.CharField(blank=True, default='', max_length=100)),
                ('width_mm', models.PositiveIntegerField(default=0)),
                ('height_mm', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('area_sqm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('min_area_sqm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('price_usd_sqm', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosquito_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Москітна сітка в замовленні',
                'verbose_name_plural': 'Москітні сітки в замовленні',
            },
        ),
    ]
