# Generated by Django 5.2.8 on 2026-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_ordermosquitocomponentitem_ordermosquitoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3, unique=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='currencyratehistory',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3),
        ),
    ]
