# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customerprofile_full_name_contact_email_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="delivery_branch",
            field=models.CharField(blank=True, max_length=255, verbose_name="Вантажне відділення (від 200кг)"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pickup_prod", "Самовивезення з виробництва"),
                    ("pickup_office", "Самовивезення з офісу"),
                    ("nova_poshta", "Нова Пошта"),
                    ("address_kyiv", "Фізична адреса (тільки м. Київ)"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="trade_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адреса торгової точки"),
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phone", models.CharField(max_length=32)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.customerprofile",
                    ),
                ),
            ],
        ),
    ]
