# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_profile_delivery_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
