# Generated by Django 5.2.8 on 2025-12-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customercontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
