# Generated by Django 5.2.8 on 2026-03-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='technical_info_files/'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
